/**
 * ImageTagEditorPage — full-width manual tag editor for a set of selected
 * images.
 *
 * Spec: ui-design.md §3.6 (Image Tag Editor), §4.4 (Tri-State Checkbox), §5
 * (Select Mode), §1 (Design tokens). Wireframes:
 *   docs/static/wireframes/06-image-tag-editor-desktop.svg
 *   docs/static/wireframes/06-image-tag-editor-mobile.svg
 *
 * Layout (desktop, left-to-right, top-to-bottom):
 *   ┌── PageHeader: "Edit Tags" + "N images selected" + Save/Cancel ──┐
 *   │ Selected images strip (horizontally scrollable thumbnails)     │
 *   │ SearchBar (filter tags) + Pending changes bar                  │
 *   │ Multi-column grid of CategorySection → TriStateCheckbox rows   │
 *   └────────────────────────────────────────────────────────────────┘
 *
 * Data sources:
 *   - Selected image ids come from `?ids=1,2,3` query param. If omitted we
 *     fall back to `selectionStore.selectedIds` — that's the path used when
 *     the user presses "Edit Tags" in the SelectionActionBar.
 *   - `useTags()` — all tags, grouped by category for the column layout.
 *   - `useTagStats(selectedIds)` — the tri-state source of truth; a tag is
 *     `checked` iff applied to ALL selected images, `indeterminate` if some,
 *     `unchecked` otherwise.
 *   - `usePendingTagChanges()` — local user edits layered over the baseline.
 *
 * Save dispatches adds and removes in one mutation. We dispatch via the
 * Wails `TagService` binding, falling back to a logged no-op stub if the
 * backend hasn't exposed the method yet (see TODO in handleSave).
 *
 * Intentionally NOT present per §3.6 prohibitions: ML panel, confidence
 * slider, character names. Characters are anime metadata on the Anime
 * Detail page, not here.
 */
import { Box, Button, Flex, Stack, Text } from "@chakra-ui/react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { ImageOff, Tag as TagIcon } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";

import { PageHeader } from "../../components/layout/page-header";
import { CategorySection } from "../../components/shared/category-section";
import { EmptyState } from "../../components/shared/empty-state";
import { ErrorAlert } from "../../components/shared/error-alert";
import { RowSkeleton } from "../../components/shared/loading-skeleton";
import { SearchBar } from "../../components/shared/search-bar";
import { ConfirmDialog } from "../../components/ui/confirm-dialog";
import { toast } from "../../components/ui/toaster";
import { TriStateCheckbox } from "../../components/ui/tri-state-checkbox";
import { useTagStats } from "../../hooks/use-tag-stats";
import { useTags } from "../../hooks/use-tags";
import { TagFrontendService } from "../../lib/api";
import {
  TAG_ONLY_CATEGORY_ORDER,
  TAG_CATEGORY_TOKENS,
  tagCategoryKey,
} from "../../lib/constants";
import { formatCount } from "../../lib/format";
import { qk } from "../../lib/query-keys";
import { useSelectionStore } from "../../stores/selection-store";
import type { Tag, TagCategoryKey } from "../../types";
import {
  deriveBaselineState,
  usePendingTagChanges,
} from "./use-pending-tag-changes";

const CATEGORY_LABELS: Record<TagCategoryKey, string> = {
  scene: "Scenes",
  nature: "Nature / Weather",
  location: "Locations",
  mood: "Mood / Genre",
  character: "Character",
  uncategorized: "Uncategorized",
};

/**
 * Parse `?ids=1,2,3` into a sorted deduped number array. Falls through
 * obviously malformed values (NaN, negatives) so the page never blows up on
 * a typo'd URL.
 */
function parseIdsParam(raw: string | null): number[] {
  if (!raw) return [];
  const out = new Set<number>();
  for (const chunk of raw.split(",")) {
    const n = Number(chunk.trim());
    if (Number.isInteger(n) && n > 0) out.add(n);
  }
  return [...out].sort((a, b) => a - b);
}

/**
 * Dispatch the pending add/remove mutation via `TagFrontendService.
 * BatchUpdateTagsForFiles`. This is the canonical binding generated by
 * wails3 from `internal/tag/frontend.go`.
 */
async function dispatchTagMutation(
  imageIds: readonly number[],
  addIds: readonly number[],
  removeIds: readonly number[],
): Promise<void> {
  if (addIds.length === 0 && removeIds.length === 0) return;
  await TagFrontendService.BatchUpdateTagsForFiles(
    [...imageIds],
    [...addIds],
    [...removeIds],
  );
}

export function ImageTagEditorPage(): JSX.Element {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  // Selection source — `?ids=...` wins if present; otherwise fall back to the
  // global selection store so "Edit Tags" from the SelectionActionBar works.
  const idsFromUrl = useMemo(
    () => parseIdsParam(searchParams.get("ids")),
    [searchParams],
  );
  const storeIds = useSelectionStore((s) => s.selectedIds);
  const selectedImageIds = useMemo(() => {
    if (idsFromUrl.length > 0) return idsFromUrl;
    return [...storeIds].sort((a, b) => a - b);
  }, [idsFromUrl, storeIds]);

  // Local state.
  const [search, setSearch] = useState("");
  const [cancelConfirmOpen, setCancelConfirmOpen] = useState(false);

  const tagsQuery = useTags();
  const statsQuery = useTagStats(selectedImageIds);
  const pending = usePendingTagChanges();

  const totalSelected = selectedImageIds.length;

  // Build a map tagId -> fileCount so we can derive the baseline for every
  // tag (including those not in stats → fileCount 0 = unchecked).
  const statsById = useMemo(() => {
    const map = new Map<number, number>();
    for (const stat of statsQuery.data ?? []) {
      map.set(stat.tagId, stat.fileCount);
    }
    return map;
  }, [statsQuery.data]);

  // Group tags by category, in the canonical display order.
  const tagsByCategory = useMemo(() => {
    const buckets = new Map<TagCategoryKey, Tag[]>();
    for (const key of TAG_ONLY_CATEGORY_ORDER) buckets.set(key, []);
    const allTags = tagsQuery.data ?? [];
    for (const tag of allTags) {
      const key = tagCategoryKey(tag.category);
      const existing = buckets.get(key) ?? [];
      existing.push(tag);
      buckets.set(key, existing);
    }
    // Sort tags alphabetically within each category so the grid is scannable.
    for (const [key, tags] of buckets) {
      buckets.set(
        key,
        [...tags].sort((a, b) => a.name.localeCompare(b.name)),
      );
    }
    return buckets;
  }, [tagsQuery.data]);

  // Apply the search filter before we render categories; hides both
  // non-matching rows and empty categories.
  const filteredByCategory = useMemo(() => {
    const needle = search.trim().toLowerCase();
    if (needle === "") return tagsByCategory;
    const result = new Map<TagCategoryKey, Tag[]>();
    for (const key of TAG_ONLY_CATEGORY_ORDER) {
      const tags = tagsByCategory.get(key) ?? [];
      const matching = tags.filter((t) =>
        t.name.toLowerCase().includes(needle),
      );
      if (matching.length > 0) result.set(key, matching);
    }
    return result;
  }, [search, tagsByCategory]);

  const saveMutation = useMutation({
    mutationFn: async () => {
      await dispatchTagMutation(
        selectedImageIds,
        [...pending.adding],
        [...pending.removing],
      );
    },
    onSuccess: () => {
      toast.success(
        "Tags updated",
        pending.count === 1
          ? "1 change applied."
          : `${pending.count} changes applied.`,
      );
      // Invalidate the stats for this selection and the global tag list so
      // downstream pages (Tag Management, image grids filtered by tag)
      // refetch.
      queryClient.invalidateQueries({
        queryKey: qk.tags.stats(selectedImageIds),
      });
      queryClient.invalidateQueries({ queryKey: qk.tags.list() });
      pending.clear();
      navigate(-1);
    },
    onError: (err: unknown) => {
      const message =
        err instanceof Error ? err.message : "Unable to save tag changes.";
      toast.error("Couldn't save tags", message);
    },
  });

  const handleSave = useCallback(() => {
    if (!pending.hasChanges || selectedImageIds.length === 0) return;
    saveMutation.mutate();
  }, [pending.hasChanges, selectedImageIds.length, saveMutation]);

  const handleCancel = useCallback(() => {
    if (pending.hasChanges) {
      setCancelConfirmOpen(true);
      return;
    }
    navigate(-1);
  }, [pending.hasChanges, navigate]);

  const handleConfirmDiscard = useCallback(() => {
    pending.clear();
    setCancelConfirmOpen(false);
    navigate(-1);
  }, [pending, navigate]);

  const headerSubtitle =
    totalSelected > 0
      ? `${formatCount(totalSelected, "image")} selected`
      : "No images selected";

  const headerActions = (
    <Flex gap="2" align="center">
      <Button
        type="button"
        size="sm"
        variant="outline"
        onClick={handleCancel}
        data-testid="image-tag-editor-cancel"
      >
        Cancel
      </Button>
      <Button
        type="button"
        size="sm"
        bg="primary"
        color="bg.surface"
        _hover={{ bg: "primary.hover" }}
        onClick={handleSave}
        disabled={!pending.hasChanges || saveMutation.isPending}
        loading={saveMutation.isPending}
        loadingText="Saving…"
        data-testid="image-tag-editor-save"
      >
        Save
      </Button>
    </Flex>
  );

  /* --------------------- render branches --------------------- */

  // Hard empty — no ids in URL or store. We bail out before calling hooks
  // for tags/stats because there is nothing to edit.
  if (totalSelected === 0) {
    return (
      <Box data-testid="image-tag-editor-page">
        <PageHeader title="Edit Tags" subtitle="No images selected" />
        <Box px={{ base: "4", md: "6" }} py="8">
          <EmptyState
            icon={ImageOff}
            title="Nothing to edit"
            description="Select at least one image, then choose Edit Tags from the action bar."
            action={
              <Button
                type="button"
                size="sm"
                variant="outline"
                onClick={() => navigate(-1)}
                data-testid="image-tag-editor-empty-back"
              >
                Go back
              </Button>
            }
          />
        </Box>
      </Box>
    );
  }

  const isLoading = tagsQuery.isLoading || statsQuery.isLoading;
  const hasError = tagsQuery.isError || statsQuery.isError;
  const errorMessage = (() => {
    if (tagsQuery.error instanceof Error) return tagsQuery.error.message;
    if (statsQuery.error instanceof Error) return statsQuery.error.message;
    return "Unable to load tag data.";
  })();

  const categoriesToRender = Array.from(filteredByCategory.entries()).filter(
    ([, tags]) => tags.length > 0,
  );

  return (
    <Box data-testid="image-tag-editor-page" position="relative">
      <PageHeader
        title="Edit Tags"
        subtitle={headerSubtitle}
        actions={headerActions}
      />

      {/* Selected images strip — small colored rectangles for each image id.
          Horizontally scrollable on narrow viewports. */}
      <Box
        as="section"
        aria-label="Selected images"
        data-testid="image-tag-editor-strip"
        px={{ base: "4", md: "6" }}
        py="3"
        bg="bg.surface"
        borderBottomWidth="1px"
        borderBottomColor="border"
        overflowX="auto"
      >
        <Flex gap="2" align="center" minWidth="max-content">
          {selectedImageIds.map((id) => (
            <Box
              key={id}
              data-testid="image-tag-editor-strip-item"
              data-file-id={id}
              flexShrink={0}
              width={{ base: "40px", md: "48px" }}
              height={{ base: "40px", md: "48px" }}
              borderRadius="sm"
              bg="primary.subtle"
              borderWidth="1px"
              borderColor="primary"
              aria-label={`Image ${id}`}
            />
          ))}
        </Flex>
      </Box>

      {/* Sticky filter + pending changes bar. */}
      <Box
        as="section"
        aria-label="Tag filters and pending changes"
        position="sticky"
        top="0"
        zIndex="dropdown"
        px={{ base: "4", md: "6" }}
        py="3"
        bg="bg.surface"
        borderBottomWidth="1px"
        borderBottomColor="border"
      >
        <Stack
          direction={{ base: "column", md: "row" }}
          gap="3"
          align={{ base: "stretch", md: "center" }}
        >
          <Box flex="1" minW={0} maxW={{ md: "420px" }}>
            <SearchBar
              value={search}
              onChange={setSearch}
              placeholder="Search tags to add or remove..."
              size="md"
            />
          </Box>
          <PendingChangesBar
            adding={pending.adding}
            removing={pending.removing}
          />
        </Stack>
      </Box>

      {/* Body: categories + tag rows. */}
      <Box
        as="section"
        aria-label="Tag categories"
        px={{ base: "4", md: "6" }}
        py="4"
      >
        {hasError && (
          <ErrorAlert
            title="Couldn't load tags"
            message={errorMessage}
            onRetry={() => {
              tagsQuery.refetch();
              statsQuery.refetch();
            }}
          />
        )}

        {!hasError && isLoading && (
          <Stack
            data-testid="image-tag-editor-loading"
            direction={{ base: "column", lg: "row" }}
            gap="6"
            aria-busy="true"
            aria-live="polite"
          >
            {[0, 1, 2].map((col) => (
              <Box key={col} flex="1" minW={0}>
                <RowSkeleton lines={4} />
                <RowSkeleton lines={4} />
              </Box>
            ))}
          </Stack>
        )}

        {!hasError && !isLoading && categoriesToRender.length === 0 && (
          <EmptyState
            icon={TagIcon}
            title={search.trim() === "" ? "No tags yet" : "No matches"}
            description={
              search.trim() === ""
                ? "Create tags from the Tags page, then return here to apply them."
                : `Nothing matches "${search.trim()}". Try a different search.`
            }
          />
        )}

        {!hasError && !isLoading && categoriesToRender.length > 0 && (
          <Box
            data-testid="image-tag-editor-grid"
            display="grid"
            gap={{ base: "4", md: "6" }}
            gridTemplateColumns={{
              base: "1fr",
              md: "repeat(2, 1fr)",
              lg: "repeat(3, 1fr)",
            }}
          >
            {categoriesToRender.map(([categoryKey, tags]) => (
              <CategorySection
                key={categoryKey}
                category={{
                  key: categoryKey,
                  label: CATEGORY_LABELS[categoryKey],
                  tagCount: tags.length,
                  color: TAG_CATEGORY_TOKENS[categoryKey].fg,
                }}
              >
                {tags.map((tag) => {
                  const fileCount = statsById.get(tag.id) ?? 0;
                  const baseline = deriveBaselineState(fileCount, totalSelected);
                  const effective = pending.getEffectiveState(tag.id, baseline);
                  return (
                    <Box
                      key={tag.id}
                      data-testid="image-tag-editor-row"
                      data-tag-id={tag.id}
                    >
                      <TriStateCheckbox
                        state={effective.state}
                        pending={effective.pending}
                        onChange={() => pending.toggle(tag.id, baseline)}
                        label={tag.name}
                        count={fileCount > 0 ? fileCount : undefined}
                      />
                      {baseline === "indeterminate" &&
                        effective.pending === null && (
                          <Text
                            fontSize="xs"
                            color="fg.muted"
                            pl="3"
                            mt="1"
                            data-testid="image-tag-editor-partial"
                          >
                            ({fileCount} of {totalSelected})
                          </Text>
                        )}
                    </Box>
                  );
                })}
              </CategorySection>
            ))}
          </Box>
        )}
      </Box>

      <ConfirmDialog
        open={cancelConfirmOpen}
        onClose={() => setCancelConfirmOpen(false)}
        onConfirm={handleConfirmDiscard}
        title="Discard changes?"
        description={`You have ${pending.count} pending change${
          pending.count === 1 ? "" : "s"
        }. Cancelling will discard them.`}
        confirmLabel="Discard"
        cancelLabel="Keep editing"
        variant="danger"
      />
    </Box>
  );
}

interface PendingChangesBarProps {
  adding: ReadonlySet<number>;
  removing: ReadonlySet<number>;
}

/** Inline summary of the user's pending edits — mirrors the wireframe's
 *  dashed indigo bar with +N / -N counts. */
function PendingChangesBar({
  adding,
  removing,
}: PendingChangesBarProps): JSX.Element {
  const total = adding.size + removing.size;
  return (
    <Flex
      data-testid="image-tag-editor-pending-bar"
      align="center"
      gap="3"
      flexWrap="wrap"
      px="3"
      py="2"
      borderRadius="md"
      borderWidth="1px"
      borderColor="primary"
      bg="primary.subtle"
      color="fg"
      fontSize="sm"
      minH="40px"
    >
      <Text fontWeight="500" color="primary" data-testid="pending-label">
        Pending:
      </Text>
      {total === 0 ? (
        <Text color="fg.muted" data-testid="pending-empty">
          No changes
        </Text>
      ) : (
        <>
          {adding.size > 0 && (
            <Box
              as="span"
              data-testid="pending-adding-count"
              px="2"
              py="0.5"
              borderRadius="pill"
              borderWidth="1px"
              borderColor="success"
              color="success"
              bg="success.bg"
              fontSize="xs"
            >
              +{adding.size} to add
            </Box>
          )}
          {removing.size > 0 && (
            <Box
              as="span"
              data-testid="pending-removing-count"
              px="2"
              py="0.5"
              borderRadius="pill"
              borderWidth="1px"
              borderColor="danger"
              color="danger"
              bg="danger.bg"
              fontSize="xs"
            >
              -{removing.size} to remove
            </Box>
          )}
          <Box flex="1" />
          <Text color="fg.muted" fontSize="xs" data-testid="pending-total">
            {total === 1 ? "1 change" : `${total} changes`}
          </Text>
        </>
      )}
    </Flex>
  );
}

export default ImageTagEditorPage;
