/**
 * Ambient module stub for the generated Wails bindings.
 *
 * `frontend/bindings/github.com/michael-freling/anime-image-viewer/internal/frontend`
 * is generated by `wails3 generate bindings` and not checked in. During type-
 * checking without the generated tree, we declare the module surface here so
 * `src/lib/api.ts` resolves. Once bindings are generated, the real .ts files
 * take precedence (TypeScript prefers source files over ambient declarations).
 *
 * The shape below mirrors `internal/frontend/*.go` DTOs. Method signatures on
 * the *Service objects are declared loosely as `unknown` function types —
 * the tight signatures will come straight from wails3 when bindings are
 * regenerated.
 */

declare module "*/bindings/github.com/michael-freling/anime-image-viewer/internal/frontend" {
  // Primitives --------------------------------------------------------------
  export interface Anime {
    id: number;
    name: string;
    aniListId: number | null;
  }

  export interface AnimeListItem {
    id: number;
    name: string;
    imageCount: number;
  }

  export interface AnimeTagInfo {
    id: number;
    name: string;
    category: string;
    imageCount: number;
  }

  export interface AnimeFolderInfo {
    id: number;
    name: string;
    path: string;
    imageCount: number;
    inherited: boolean;
  }

  export interface AnimeFolderTreeNode {
    id: number;
    name: string;
    imageCount: number;
    children: AnimeFolderTreeNode[];
  }

  export interface AnimeEntryInfo {
    id: number;
    name: string;
    entryType: string;
    entryNumber: number | null;
    airingSeason: string;
    airingYear: number | null;
    imageCount: number;
    children: AnimeEntryInfo[];
  }

  export interface UnassignedFolder {
    id: number;
    name: string;
  }

  export interface FolderAnimeStatus {
    folderId: number;
    animeId: number;
    stored: boolean;
    inherited: boolean;
  }

  export interface AniListSearchResult {
    id: number;
    titleRomaji: string;
    titleEnglish: string;
    titleNative: string;
    format: string;
    status: string;
    season: string;
    seasonYear: number;
    episodes: number;
    coverImageUrl: string;
  }

  export interface AniListImportResult {
    entriesCreated: number;
    charactersCreated: number;
  }

  export interface AnimeDetailsResponse {
    anime: Anime;
    tags: AnimeTagInfo[];
    folders: AnimeFolderInfo[];
    folderTree: AnimeFolderTreeNode | null;
    entries: AnimeEntryInfo[];
  }

  export interface SearchImagesRequest {
    directoryId?: number;
    tagId?: number;
    isInvertedTagSearch?: boolean;
  }

  export interface Image {
    id: number;
    name: string;
    path: string;
  }

  export interface SearchImagesResponse {
    images: Image[] | null;
  }

  export interface Tag {
    id: number;
    name: string;
    category: string;
  }

  export interface TagStat {
    fileCount: number;
    isAddedBySelectedFiles: boolean;
  }

  export interface ReadTagsByFileIDsResponse {
    tagStats: Record<number, TagStat> | null;
  }

  export interface BackupInfo {
    createdAt: string;
    includesImages: boolean;
    path: string;
  }

  export interface BackupConfig {
    backupDirectory: string;
    retentionCount: number;
    idleBackupEnabled: boolean;
    idleMinutes: number;
  }

  export interface ConfigSettings {
    imageRootDirectory: string;
    configDirectory: string;
    logDirectory: string;
    backupDirectory: string;
    retentionCount: number;
    idleBackupEnabled: boolean;
    idleBackupIncludeImages: boolean;
    idleMinutes: number;
  }

  export interface ImportProgressEventFailure {
    path: string;
    error: string;
  }

  export interface ImportProgressEvent {
    total: number;
    completed: number;
    failed: number;
    failures: ImportProgressEventFailure[];
  }

  export interface Directory {
    id: number;
    name: string;
    path: string;
    children: Directory[] | null;
  }

  export interface ReadDirectoryTreeResponse {
    rootDirectory: Directory;
    tagMap: Record<number, number[]> | null;
  }

  // Service surfaces --------------------------------------------------------
  // Method bodies are generated by wails3; declare as record-like namespaces
  // so the re-exports in lib/api.ts type-check without pinning us to a stale
  // signature. Downstream hooks in later phases will import the regenerated
  // strongly-typed versions once `task generate:bindings` has run.
  export const AnimeService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const TagService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const ImageService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const SearchService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const BackupFrontendService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const ConfigFrontendService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const BatchImportImageService: Record<string, (...args: unknown[]) => Promise<unknown>>;
  export const DirectoryService: Record<string, (...args: unknown[]) => Promise<unknown>>;
}
